### PR TITLE
Update for 1.19

### PR DESCRIPTION
**Pull request by brandonplank**

### CODE REVIEW

**Comment by LordVertice** [comment]
Sorry, not working for me. As far as I can tell it built successfully but the dupe buttons don't show up in game. Maybe I did it wrong?

**Comment by jan-Sanku** [comment]
Confirmed to work in 1.19!
For anyone who doesn't know how to build, [here's the JAR to put in your mods folder](https://www.mediafire.com/file/mefzcfz1czghdwk/shulker-dupe-1.0.1.jar/file) (I promise it's safe lol)

**Comment by buiawpkgew1** [comment]
forge？

**Comment by Coderx-Gamer** [comment]
sorry i was sick a few days ago and was too lazy to update it thanks for updating it lol

**Pull request merged**
